apiVersion: v1
kind: Pod
metadata:
  name: broken-pod
spec:
  containers:
    - name: test
      image: thisimagedoesnotexist:latest  # Imagem inexistente
      ports:
        - containerPort: 80
  tolerations: []  # Nenhuma toler창ncia adicionada
  nodeSelector:
    dedicated: "gpu"  # Sup천e-se que n찾o exista n처 com essa label

