apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaset-example
spec:
  replicas: 3
  selector:
    matchLabels:
      app: replicaset-app  # Adicionando um label selector válido
  template:
    metadata:
      labels:
        app: replicaset-app
    spec:
      containers:
        - name: app-container
          image: nginx
          ports:
            - containerPort: 80

